/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainIndexImport } from './routes/_main/index'

// Create Virtual Routes

const AuthAuthLazyImport = createFileRoute('/_auth/auth')()
const MainWorkScheduleIndexLazyImport = createFileRoute(
  '/_main/work-schedule/',
)()
const MainRouteIndexLazyImport = createFileRoute('/_main/route/')()
const MainOrdersIndexLazyImport = createFileRoute('/_main/orders/')()
const MainFinanceIndexLazyImport = createFileRoute('/_main/finance/')()
const MainSettingsWarehouseLazyImport = createFileRoute(
  '/_main/settings/warehouse',
)()
const MainSettingsShippersLazyImport = createFileRoute(
  '/_main/settings/shippers',
)()
const MainSettingsProductsLazyImport = createFileRoute(
  '/_main/settings/products',
)()
const MainSettingsLogisticiansLazyImport = createFileRoute(
  '/_main/settings/logisticians',
)()
const MainSettingsFreightForwardersLazyImport = createFileRoute(
  '/_main/settings/freight-forwarders',
)()
const MainSettingsDriversLazyImport = createFileRoute(
  '/_main/settings/drivers',
)()
const MainSettingsCustomersLazyImport = createFileRoute(
  '/_main/settings/customers',
)()
const MainSettingsCarsLazyImport = createFileRoute('/_main/settings/cars')()
const MainReportsLogisticiansIndexLazyImport = createFileRoute(
  '/_main/reports/logisticians/',
)()
const MainReportsFreightForwardersIndexLazyImport = createFileRoute(
  '/_main/reports/freight-forwarders/',
)()
const MainReportsDriversIndexLazyImport = createFileRoute(
  '/_main/reports/drivers/',
)()
const MainReportsCarsIndexLazyImport = createFileRoute('/_main/reports/cars/')()
const MainReportsAgentsIndexLazyImport = createFileRoute(
  '/_main/reports/agents/',
)()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const AuthAuthLazyRoute = AuthAuthLazyImport.update({
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/auth.lazy').then((d) => d.Route))

const MainWorkScheduleIndexLazyRoute = MainWorkScheduleIndexLazyImport.update({
  path: '/work-schedule/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/work-schedule/index.lazy').then((d) => d.Route),
)

const MainRouteIndexLazyRoute = MainRouteIndexLazyImport.update({
  path: '/route/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/route/index.lazy').then((d) => d.Route),
)

const MainOrdersIndexLazyRoute = MainOrdersIndexLazyImport.update({
  path: '/orders/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/orders/index.lazy').then((d) => d.Route),
)

const MainFinanceIndexLazyRoute = MainFinanceIndexLazyImport.update({
  path: '/finance/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/finance/index.lazy').then((d) => d.Route),
)

const MainSettingsWarehouseLazyRoute = MainSettingsWarehouseLazyImport.update({
  path: '/settings/warehouse',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings/warehouse.lazy').then((d) => d.Route),
)

const MainSettingsShippersLazyRoute = MainSettingsShippersLazyImport.update({
  path: '/settings/shippers',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings/shippers.lazy').then((d) => d.Route),
)

const MainSettingsProductsLazyRoute = MainSettingsProductsLazyImport.update({
  path: '/settings/products',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings/products.lazy').then((d) => d.Route),
)

const MainSettingsLogisticiansLazyRoute =
  MainSettingsLogisticiansLazyImport.update({
    path: '/settings/logisticians',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/settings/logisticians.lazy').then((d) => d.Route),
  )

const MainSettingsFreightForwardersLazyRoute =
  MainSettingsFreightForwardersLazyImport.update({
    path: '/settings/freight-forwarders',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/settings/freight-forwarders.lazy').then(
      (d) => d.Route,
    ),
  )

const MainSettingsDriversLazyRoute = MainSettingsDriversLazyImport.update({
  path: '/settings/drivers',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings/drivers.lazy').then((d) => d.Route),
)

const MainSettingsCustomersLazyRoute = MainSettingsCustomersLazyImport.update({
  path: '/settings/customers',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings/customers.lazy').then((d) => d.Route),
)

const MainSettingsCarsLazyRoute = MainSettingsCarsLazyImport.update({
  path: '/settings/cars',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings/cars.lazy').then((d) => d.Route),
)

const MainReportsLogisticiansIndexLazyRoute =
  MainReportsLogisticiansIndexLazyImport.update({
    path: '/reports/logisticians/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/reports/logisticians/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainReportsFreightForwardersIndexLazyRoute =
  MainReportsFreightForwardersIndexLazyImport.update({
    path: '/reports/freight-forwarders/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/reports/freight-forwarders/index.lazy').then(
      (d) => d.Route,
    ),
  )

const MainReportsDriversIndexLazyRoute =
  MainReportsDriversIndexLazyImport.update({
    path: '/reports/drivers/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/reports/drivers/index.lazy').then((d) => d.Route),
  )

const MainReportsCarsIndexLazyRoute = MainReportsCarsIndexLazyImport.update({
  path: '/reports/cars/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/reports/cars/index.lazy').then((d) => d.Route),
)

const MainReportsAgentsIndexLazyRoute = MainReportsAgentsIndexLazyImport.update(
  {
    path: '/reports/agents/',
    getParentRoute: () => MainRoute,
  } as any,
).lazy(() =>
  import('./routes/_main/reports/agents/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLazyImport
      parentRoute: typeof AuthImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/cars': {
      id: '/_main/settings/cars'
      path: '/settings/cars'
      fullPath: '/settings/cars'
      preLoaderRoute: typeof MainSettingsCarsLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/customers': {
      id: '/_main/settings/customers'
      path: '/settings/customers'
      fullPath: '/settings/customers'
      preLoaderRoute: typeof MainSettingsCustomersLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/drivers': {
      id: '/_main/settings/drivers'
      path: '/settings/drivers'
      fullPath: '/settings/drivers'
      preLoaderRoute: typeof MainSettingsDriversLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/freight-forwarders': {
      id: '/_main/settings/freight-forwarders'
      path: '/settings/freight-forwarders'
      fullPath: '/settings/freight-forwarders'
      preLoaderRoute: typeof MainSettingsFreightForwardersLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/logisticians': {
      id: '/_main/settings/logisticians'
      path: '/settings/logisticians'
      fullPath: '/settings/logisticians'
      preLoaderRoute: typeof MainSettingsLogisticiansLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/products': {
      id: '/_main/settings/products'
      path: '/settings/products'
      fullPath: '/settings/products'
      preLoaderRoute: typeof MainSettingsProductsLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/shippers': {
      id: '/_main/settings/shippers'
      path: '/settings/shippers'
      fullPath: '/settings/shippers'
      preLoaderRoute: typeof MainSettingsShippersLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/settings/warehouse': {
      id: '/_main/settings/warehouse'
      path: '/settings/warehouse'
      fullPath: '/settings/warehouse'
      preLoaderRoute: typeof MainSettingsWarehouseLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/finance/': {
      id: '/_main/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof MainFinanceIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/orders/': {
      id: '/_main/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof MainOrdersIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/route/': {
      id: '/_main/route/'
      path: '/route'
      fullPath: '/route'
      preLoaderRoute: typeof MainRouteIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/work-schedule/': {
      id: '/_main/work-schedule/'
      path: '/work-schedule'
      fullPath: '/work-schedule'
      preLoaderRoute: typeof MainWorkScheduleIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/reports/agents/': {
      id: '/_main/reports/agents/'
      path: '/reports/agents'
      fullPath: '/reports/agents'
      preLoaderRoute: typeof MainReportsAgentsIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/reports/cars/': {
      id: '/_main/reports/cars/'
      path: '/reports/cars'
      fullPath: '/reports/cars'
      preLoaderRoute: typeof MainReportsCarsIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/reports/drivers/': {
      id: '/_main/reports/drivers/'
      path: '/reports/drivers'
      fullPath: '/reports/drivers'
      preLoaderRoute: typeof MainReportsDriversIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/reports/freight-forwarders/': {
      id: '/_main/reports/freight-forwarders/'
      path: '/reports/freight-forwarders'
      fullPath: '/reports/freight-forwarders'
      preLoaderRoute: typeof MainReportsFreightForwardersIndexLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/reports/logisticians/': {
      id: '/_main/reports/logisticians/'
      path: '/reports/logisticians'
      fullPath: '/reports/logisticians'
      preLoaderRoute: typeof MainReportsLogisticiansIndexLazyImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthLazyRoute: typeof AuthAuthLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLazyRoute: AuthAuthLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainSettingsCarsLazyRoute: typeof MainSettingsCarsLazyRoute
  MainSettingsCustomersLazyRoute: typeof MainSettingsCustomersLazyRoute
  MainSettingsDriversLazyRoute: typeof MainSettingsDriversLazyRoute
  MainSettingsFreightForwardersLazyRoute: typeof MainSettingsFreightForwardersLazyRoute
  MainSettingsLogisticiansLazyRoute: typeof MainSettingsLogisticiansLazyRoute
  MainSettingsProductsLazyRoute: typeof MainSettingsProductsLazyRoute
  MainSettingsShippersLazyRoute: typeof MainSettingsShippersLazyRoute
  MainSettingsWarehouseLazyRoute: typeof MainSettingsWarehouseLazyRoute
  MainFinanceIndexLazyRoute: typeof MainFinanceIndexLazyRoute
  MainOrdersIndexLazyRoute: typeof MainOrdersIndexLazyRoute
  MainRouteIndexLazyRoute: typeof MainRouteIndexLazyRoute
  MainWorkScheduleIndexLazyRoute: typeof MainWorkScheduleIndexLazyRoute
  MainReportsAgentsIndexLazyRoute: typeof MainReportsAgentsIndexLazyRoute
  MainReportsCarsIndexLazyRoute: typeof MainReportsCarsIndexLazyRoute
  MainReportsDriversIndexLazyRoute: typeof MainReportsDriversIndexLazyRoute
  MainReportsFreightForwardersIndexLazyRoute: typeof MainReportsFreightForwardersIndexLazyRoute
  MainReportsLogisticiansIndexLazyRoute: typeof MainReportsLogisticiansIndexLazyRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainSettingsCarsLazyRoute: MainSettingsCarsLazyRoute,
  MainSettingsCustomersLazyRoute: MainSettingsCustomersLazyRoute,
  MainSettingsDriversLazyRoute: MainSettingsDriversLazyRoute,
  MainSettingsFreightForwardersLazyRoute:
    MainSettingsFreightForwardersLazyRoute,
  MainSettingsLogisticiansLazyRoute: MainSettingsLogisticiansLazyRoute,
  MainSettingsProductsLazyRoute: MainSettingsProductsLazyRoute,
  MainSettingsShippersLazyRoute: MainSettingsShippersLazyRoute,
  MainSettingsWarehouseLazyRoute: MainSettingsWarehouseLazyRoute,
  MainFinanceIndexLazyRoute: MainFinanceIndexLazyRoute,
  MainOrdersIndexLazyRoute: MainOrdersIndexLazyRoute,
  MainRouteIndexLazyRoute: MainRouteIndexLazyRoute,
  MainWorkScheduleIndexLazyRoute: MainWorkScheduleIndexLazyRoute,
  MainReportsAgentsIndexLazyRoute: MainReportsAgentsIndexLazyRoute,
  MainReportsCarsIndexLazyRoute: MainReportsCarsIndexLazyRoute,
  MainReportsDriversIndexLazyRoute: MainReportsDriversIndexLazyRoute,
  MainReportsFreightForwardersIndexLazyRoute:
    MainReportsFreightForwardersIndexLazyRoute,
  MainReportsLogisticiansIndexLazyRoute: MainReportsLogisticiansIndexLazyRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/': typeof MainIndexRoute
  '/settings/cars': typeof MainSettingsCarsLazyRoute
  '/settings/customers': typeof MainSettingsCustomersLazyRoute
  '/settings/drivers': typeof MainSettingsDriversLazyRoute
  '/settings/freight-forwarders': typeof MainSettingsFreightForwardersLazyRoute
  '/settings/logisticians': typeof MainSettingsLogisticiansLazyRoute
  '/settings/products': typeof MainSettingsProductsLazyRoute
  '/settings/shippers': typeof MainSettingsShippersLazyRoute
  '/settings/warehouse': typeof MainSettingsWarehouseLazyRoute
  '/finance': typeof MainFinanceIndexLazyRoute
  '/orders': typeof MainOrdersIndexLazyRoute
  '/route': typeof MainRouteIndexLazyRoute
  '/work-schedule': typeof MainWorkScheduleIndexLazyRoute
  '/reports/agents': typeof MainReportsAgentsIndexLazyRoute
  '/reports/cars': typeof MainReportsCarsIndexLazyRoute
  '/reports/drivers': typeof MainReportsDriversIndexLazyRoute
  '/reports/freight-forwarders': typeof MainReportsFreightForwardersIndexLazyRoute
  '/reports/logisticians': typeof MainReportsLogisticiansIndexLazyRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/': typeof MainIndexRoute
  '/settings/cars': typeof MainSettingsCarsLazyRoute
  '/settings/customers': typeof MainSettingsCustomersLazyRoute
  '/settings/drivers': typeof MainSettingsDriversLazyRoute
  '/settings/freight-forwarders': typeof MainSettingsFreightForwardersLazyRoute
  '/settings/logisticians': typeof MainSettingsLogisticiansLazyRoute
  '/settings/products': typeof MainSettingsProductsLazyRoute
  '/settings/shippers': typeof MainSettingsShippersLazyRoute
  '/settings/warehouse': typeof MainSettingsWarehouseLazyRoute
  '/finance': typeof MainFinanceIndexLazyRoute
  '/orders': typeof MainOrdersIndexLazyRoute
  '/route': typeof MainRouteIndexLazyRoute
  '/work-schedule': typeof MainWorkScheduleIndexLazyRoute
  '/reports/agents': typeof MainReportsAgentsIndexLazyRoute
  '/reports/cars': typeof MainReportsCarsIndexLazyRoute
  '/reports/drivers': typeof MainReportsDriversIndexLazyRoute
  '/reports/freight-forwarders': typeof MainReportsFreightForwardersIndexLazyRoute
  '/reports/logisticians': typeof MainReportsLogisticiansIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/auth': typeof AuthAuthLazyRoute
  '/_main/': typeof MainIndexRoute
  '/_main/settings/cars': typeof MainSettingsCarsLazyRoute
  '/_main/settings/customers': typeof MainSettingsCustomersLazyRoute
  '/_main/settings/drivers': typeof MainSettingsDriversLazyRoute
  '/_main/settings/freight-forwarders': typeof MainSettingsFreightForwardersLazyRoute
  '/_main/settings/logisticians': typeof MainSettingsLogisticiansLazyRoute
  '/_main/settings/products': typeof MainSettingsProductsLazyRoute
  '/_main/settings/shippers': typeof MainSettingsShippersLazyRoute
  '/_main/settings/warehouse': typeof MainSettingsWarehouseLazyRoute
  '/_main/finance/': typeof MainFinanceIndexLazyRoute
  '/_main/orders/': typeof MainOrdersIndexLazyRoute
  '/_main/route/': typeof MainRouteIndexLazyRoute
  '/_main/work-schedule/': typeof MainWorkScheduleIndexLazyRoute
  '/_main/reports/agents/': typeof MainReportsAgentsIndexLazyRoute
  '/_main/reports/cars/': typeof MainReportsCarsIndexLazyRoute
  '/_main/reports/drivers/': typeof MainReportsDriversIndexLazyRoute
  '/_main/reports/freight-forwarders/': typeof MainReportsFreightForwardersIndexLazyRoute
  '/_main/reports/logisticians/': typeof MainReportsLogisticiansIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/'
    | '/settings/cars'
    | '/settings/customers'
    | '/settings/drivers'
    | '/settings/freight-forwarders'
    | '/settings/logisticians'
    | '/settings/products'
    | '/settings/shippers'
    | '/settings/warehouse'
    | '/finance'
    | '/orders'
    | '/route'
    | '/work-schedule'
    | '/reports/agents'
    | '/reports/cars'
    | '/reports/drivers'
    | '/reports/freight-forwarders'
    | '/reports/logisticians'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth'
    | '/'
    | '/settings/cars'
    | '/settings/customers'
    | '/settings/drivers'
    | '/settings/freight-forwarders'
    | '/settings/logisticians'
    | '/settings/products'
    | '/settings/shippers'
    | '/settings/warehouse'
    | '/finance'
    | '/orders'
    | '/route'
    | '/work-schedule'
    | '/reports/agents'
    | '/reports/cars'
    | '/reports/drivers'
    | '/reports/freight-forwarders'
    | '/reports/logisticians'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/auth'
    | '/_main/'
    | '/_main/settings/cars'
    | '/_main/settings/customers'
    | '/_main/settings/drivers'
    | '/_main/settings/freight-forwarders'
    | '/_main/settings/logisticians'
    | '/_main/settings/products'
    | '/_main/settings/shippers'
    | '/_main/settings/warehouse'
    | '/_main/finance/'
    | '/_main/orders/'
    | '/_main/route/'
    | '/_main/work-schedule/'
    | '/_main/reports/agents/'
    | '/_main/reports/cars/'
    | '/_main/reports/drivers/'
    | '/_main/reports/freight-forwarders/'
    | '/_main/reports/logisticians/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/",
        "/_main/settings/cars",
        "/_main/settings/customers",
        "/_main/settings/drivers",
        "/_main/settings/freight-forwarders",
        "/_main/settings/logisticians",
        "/_main/settings/products",
        "/_main/settings/shippers",
        "/_main/settings/warehouse",
        "/_main/finance/",
        "/_main/orders/",
        "/_main/route/",
        "/_main/work-schedule/",
        "/_main/reports/agents/",
        "/_main/reports/cars/",
        "/_main/reports/drivers/",
        "/_main/reports/freight-forwarders/",
        "/_main/reports/logisticians/"
      ]
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.lazy.tsx",
      "parent": "/_auth"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/settings/cars": {
      "filePath": "_main/settings/cars.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/settings/customers": {
      "filePath": "_main/settings/customers.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/settings/drivers": {
      "filePath": "_main/settings/drivers.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/settings/freight-forwarders": {
      "filePath": "_main/settings/freight-forwarders.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/settings/logisticians": {
      "filePath": "_main/settings/logisticians.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/settings/products": {
      "filePath": "_main/settings/products.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/settings/shippers": {
      "filePath": "_main/settings/shippers.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/settings/warehouse": {
      "filePath": "_main/settings/warehouse.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/finance/": {
      "filePath": "_main/finance/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/orders/": {
      "filePath": "_main/orders/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/route/": {
      "filePath": "_main/route/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/work-schedule/": {
      "filePath": "_main/work-schedule/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/reports/agents/": {
      "filePath": "_main/reports/agents/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/reports/cars/": {
      "filePath": "_main/reports/cars/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/reports/drivers/": {
      "filePath": "_main/reports/drivers/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/reports/freight-forwarders/": {
      "filePath": "_main/reports/freight-forwarders/index.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/reports/logisticians/": {
      "filePath": "_main/reports/logisticians/index.lazy.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
